Repository jpbede/aiotankerkoenig, pull requests merged in 2024-02, with the labels that each got.

#38 Raise dedicated time out error
  aiotankerkoenig/__init__.py
  aiotankerkoenig/aiotankerkoenig.py
  aiotankerkoenig/exceptions.py
  tests/test_aiotankerkoenig.py
Labels: enhancement

#39 Add guard against non-200 HTTP responses
  aiotankerkoenig/aiotankerkoenig.py
  tests/test_aiotankerkoenig.py
Labels: enhancement, minor

#40 Add missing permissions to lock workflow
  .github/workflows/lock.yml
Labels: ci

#43 Add buymeacoffee.com link
  .github/FUNDING.yml
Labels: maintenance

#62 Use timeout settings from ClientSession
  aiotankerkoenig/aiotankerkoenig.py
  tests/test_aiotankerkoenig.py
Labels: bugfix

#64 Re-add timeout test
  tests/test_aiotankerkoenig.py
Labels: enhancement

#65 Use status instead of deprecated code property
  aiotankerkoenig/aiotankerkoenig.py
Labels: enhancement
